# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('perc', models.CharField(choices=[(1, '0%'), (25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')], max_length=10)),
            ],
        ),
    ]
