# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Works_images',
            new_name='WorksImages',
        ),
        migrations.AlterField(
            model_name='experience',
            name='perc',
            field=models.IntegerField(choices=[(1, '0%'), (10, '10%'), (20, '20%'), (25, '25%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (75, '75%'), (80, '80%'), (90, '90%'), (100, '100%')]),
        ),
    ]
