# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='perc',
            field=models.IntegerField(choices=[(1, '0%'), (25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')]),
        ),
    ]
