# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_auto_20171031_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='level',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
