# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_auto_20171031_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksimages',
            name='file',
            field=models.FileField(upload_to='sections/static/sections/images/portfolio/'),
        ),
    ]
