# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_auto_20171031_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksimages',
            name='file',
            field=models.ImageField(upload_to='portfolio'),
        ),
    ]
