# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_auto_20171031_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Works',
            new_name='Work',
        ),
        migrations.RenameModel(
            old_name='WorksImages',
            new_name='Work_Image',
        ),
    ]
