# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0007_auto_20171031_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_image',
            name='file',
            field=models.ImageField(upload_to='uploads/portfolio'),
        ),
    ]
